Repository armory3d/armory, pull requests merged in 2022-09, with the labels that each got.

#2574 [HL] Fix int overflow in Nishita LUT calculations
  Sources/armory/renderpath/Nishita.hx
Labels: Release Notes: Fixes

#2573 Fix rigid body angular/ rolling friction
  Sources/armory/logicnode/AddRigidBodyNode.hx
  Sources/armory/trait/physics/bullet/RigidBody.hx
  blender/arm/exporter.py
  blender/arm/logicnode/physics/LN_Add_rigid_body.py
  blender/arm/props.py
  blender/arm/props_ui.py
  blender/arm/utils.py
Labels: Release Notes: Fixes

#2544 Water ssr
  Shaders/water_pass/water_pass.frag.glsl
  Shaders/water_pass/water_pass.json
  Sources/armory/renderpath/RenderPathDeferred.hx
  blender/arm/make_renderpath.py
Labels: Release Notes: Changes

#2565 Support for Blender 3.3 LTS
  blender/arm/api.py
  blender/arm/exporter.py
  blender/arm/exporter_opt.py
  blender/arm/handlers.py
  blender/arm/logicnode/arm_sockets.py
  blender/arm/material/cycles_nodes/nodes_input.py
  blender/arm/material/cycles_nodes/nodes_shader.py
  blender/arm/material/mat_utils.py
  blender/arm/props.py
  blender/arm/props_renderpath.py
  blender/arm/props_traits.py
  blender/arm/props_traits_props.py
  blender/arm/props_ui.py
  blender/arm/proxy.py
  blender/arm/utils.py
  blender/arm/write_probes.py
Labels: Blender 3.3 LTS

#2577 Fix arm material parameter export
  blender/arm/material/cycles_nodes/nodes_input.py
  blender/arm/material/shader.py
Labels: Release Notes: Fixes

#2583 Fix support for Separate/Combine Color nodes
  blender/arm/material/cycles.py
  blender/arm/material/cycles_nodes/nodes_converter.py
Labels: Release Notes: Fixes

#2584 Fix rigid body copy parameters
  blender/arm/handlers.py
Labels: Release Notes: Fixes

#2585 Draw to material image texture
  Sources/armory/logicnode/CreateRenderTargetNode.hx
  Sources/armory/logicnode/DrawArcNode.hx
  Sources/armory/logicnode/DrawCircleNode.hx
  Sources/armory/logicnode/DrawCurveNode.hx
  Sources/armory/logicnode/DrawImageNode.hx
  Sources/armory/logicnode/DrawLineNode.hx
  Sources/armory/logicnode/DrawPolygonNode.hx
  Sources/armory/logicnode/DrawRectNode.hx
  Sources/armory/logicnode/DrawStringNode.hx
  Sources/armory/logicnode/DrawToMaterialImageNode.hx
  Sources/armory/logicnode/DrawTriangleNode.hx
  Sources/armory/logicnode/OnRender2DNode.hx
  Sources/armory/renderpath/RenderToTexture.hx
  Sources/armory/trait/internal/UniformsManager.hx
  blender/arm/logicnode/renderpath/LN_create_render_target.py
  blender/arm/logicnode/renderpath/LN_draw_to_material_image.py
Labels: Release Notes: Changes

#2586 Fix exception when drawing the UI for bundled traits
  blender/arm/handlers.py
  blender/arm/props_traits.py
Labels: Release Notes: Fixes

#2587 Support multiple canvas onReady callbacks
  Sources/armory/logicnode/CanvasGetLocationNode.hx
  Sources/armory/logicnode/CanvasGetPBNode.hx
  Sources/armory/logicnode/CanvasGetRotationNode.hx
  Sources/armory/logicnode/CanvasGetScaleNode.hx
  Sources/armory/logicnode/CanvasSetAssetNode.hx
  Sources/armory/logicnode/CanvasSetCheckBoxNode.hx
  Sources/armory/logicnode/CanvasSetInputTextNode.hx
  Sources/armory/logicnode/CanvasSetLocationNode.hx
  Sources/armory/logicnode/CanvasSetPBNode.hx
  Sources/armory/logicnode/CanvasSetProgressBarColorNode.hx
  Sources/armory/logicnode/CanvasSetRotationNode.hx
  Sources/armory/logicnode/CanvasSetScaleNode.hx
  Sources/armory/logicnode/CanvasSetSliderNode.hx
  Sources/armory/logicnode/CanvasSetTextColorNode.hx
  Sources/armory/logicnode/CanvasSetTextNode.hx
  Sources/armory/logicnode/CanvasSetVisibleNode.hx
  Sources/armory/trait/internal/CanvasScript.hx
Labels: Release Notes: Changes

#2589 New node for setting canvas input text focus
  Sources/armory/logicnode/CanvasSetInputTextFocusNode.hx
  Sources/armory/trait/internal/CanvasScript.hx
  blender/arm/logicnode/canvas/LN_set_canvas_input_text_focus.py
Labels: Release Notes: Changes

#2588 Fix compilation of PhysicsBreak.hx
  Sources/armory/trait/PhysicsBreak.hx
  Sources/armory/trait/physics/bullet/RigidBody.hx
Labels: Release Notes: Fixes

#2590 fix webassemblystudio link
  blender/arm/props_traits.py
Labels: Release Notes: Fixes

#2591 Upgrade for remove object node
  Sources/armory/logicnode/RemoveObjectNode.hx
  blender/arm/logicnode/object/LN_remove_object.py
Labels: Release Notes: Changes

#2594 Edit scripts button: use Haxe icon instead of Python icon
  blender/arm/props_traits.py
Labels: Release Notes: Changes

#2593 Canvas: fix theme issues when Zui theme == canvas theme
  Sources/armory/ui/Canvas.hx
Labels: Release Notes: Fixes

#2600 Add tree variables to scene node
  blender/arm/logicnode/scene/LN_scene.py
  blender/arm/logicnode/variable/LN_scene.py
Labels: Release Notes: Changes

#2599 [windows-hl] Fix "After Publish" actions and add "Open in Visual Studio" operator
  blender/arm/handlers.py
  blender/arm/log.py
  blender/arm/make.py
  blender/arm/props.py
  blender/arm/props_exporter.py
  blender/arm/props_ui.py
  blender/arm/utils.py
  blender/arm/utils_vs.py
  blender/start.py
Labels: Release Notes: Changes

#2597 Fix editing values in debug console
  Sources/armory/trait/internal/DebugConsole.hx
Labels: Release Notes: Fixes

#2602 Start browser using proc_play
  blender/arm/make.py
Labels: Release Notes: Changes

#2596 Add option to automatically decide amount of Khamake processes
  blender/arm/make.py
  blender/arm/utils.py
Labels: Release Notes: Changes

#2601 Debug Console: show active camera in outliner and hide "Set Active Camera" button for active cameras
  Sources/armory/trait/internal/DebugConsole.hx
Labels: Release Notes: Changes

#2603 Warn about precision issues for very large UV coordinates
  blender/arm/exporter.py
  blender/arm/exporter_opt.py
Labels: Release Notes: Changes

#2604 Update the Lightmapper to support Blender 3.3
  blender/arm/lightmapper/utility/build.py
  blender/arm/lightmapper/utility/cycles/lightmap.py
  blender/arm/lightmapper/utility/cycles/prepare.py
  blender/arm/lightmapper/utility/denoiser/oidn.py
  blender/arm/lightmapper/utility/denoiser/optix.py
  blender/arm/lightmapper/utility/utility.py
Labels: Release Notes: Fixes, Blender 3.3 LTS

#2605 Custom play launch commands
  blender/arm/make.py
Labels: Release Notes: Changes

#2608 Add new "Set Canvas Color" node
  Sources/armory/logicnode/CanvasSetColorNode.hx
  Sources/armory/logicnode/CanvasSetProgressBarColorNode.hx
  Sources/armory/logicnode/CanvasSetTextColorNode.hx
  blender/arm/logicnode/canvas/LN_set_canvas_color.py
  blender/arm/logicnode/canvas/LN_set_canvas_progress_bar_color.py
  blender/arm/logicnode/canvas/LN_set_canvas_text_color.py
  blender/arm/logicnode/deprecated/LN_set_canvas_progress_bar_color.py
  blender/arm/logicnode/deprecated/LN_set_canvas_text_color.py
  blender/arm/logicnode/replacement.py
Labels: Release Notes: Changes
