Repository armory3d/armory, pull requests merged in 2022-10, with the labels that each got.

#2615 Fix building for Krom on Windows
  blender/arm/make.py
Labels: Release Notes: Fixes

#2614 New "Combine RGBA" node and add alpha output to "Separate RGB" node
  Sources/armory/logicnode/CombineColorNode.hx
  Sources/armory/logicnode/SeparateColorNode.hx
  blender/arm/logicnode/math/LN_combine_rgb.py
  blender/arm/logicnode/math/LN_separate_rgb.py
Labels: Release Notes: Changes

#2617 Add option to set playback volume
  Sources/armory/logicnode/PlaySoundRawNode.hx
  blender/arm/logicnode/sound/LN_play_sound.py
Labels: Release Notes: Changes

#2606 Fix socket indices of Principled BSDF node
  blender/arm/material/cycles_nodes/nodes_shader.py
Labels: Release Notes: Fixes, Blender 3.3 LTS

#2623 Add option for NavAgent height offset
  Sources/armory/logicnode/GoToLocationNode.hx
  Sources/armory/trait/NavAgent.hx
  Sources/armory/trait/NavMesh.hx
  blender/arm/logicnode/navmesh/LN_go_to_location.py
Labels: Release Notes: Changes

#2620 Disp color mix
  blender/arm/material/make_tess.py
Labels: Release Notes: Fixes
