Repository armory3d/armory, pull requests merged in 2022-08, with the labels that each got.

#2538 Tree variables: fix missing synchronization when adding getters/setters
  blender/arm/logicnode/arm_nodes.py
  blender/arm/logicnode/tree_variables.py
  blender/arm/make_logic.py
  blender/arm/props.py
Labels: Release Notes: Fixes

#2540 Fix initialization of tween and group nodes and ensure correct file version numbers
  blender/arm/handlers.py
  blender/arm/logicnode/arm_nodes.py
  blender/arm/logicnode/math/LN_tween_float.py
  blender/arm/logicnode/math/LN_tween_rotation.py
  blender/arm/logicnode/math/LN_tween_transform.py
  blender/arm/logicnode/math/LN_tween_vector.py
  blender/arm/logicnode/miscellaneous/LN_group_input.py
  blender/arm/logicnode/miscellaneous/LN_group_output.py
  blender/arm/props.py
  blender/arm/props_ui.py
Labels: Release Notes: Fixes

#2548 Fix sleep node
  Sources/armory/logicnode/SleepNode.hx
Labels: Release Notes: Fixes

#2546 Fix "Set Scene Active" node when using asset compression
  Sources/armory/logicnode/SetSceneNode.hx
Labels: Release Notes: Fixes

#2553 Fix depth buffer access in SSS pass & fix numerical robustness of packFloatInt16()
  Shaders/deferred_light/deferred_light.frag.glsl
  Shaders/deferred_light_mobile/deferred_light.frag.glsl
  Shaders/probe_cubemap/probe_cubemap.frag.glsl
  Shaders/probe_planar/probe_planar.frag.glsl
  Shaders/std/gbuffer.glsl
  Sources/armory/renderpath/RenderPathDeferred.hx
Labels: Release Notes: Fixes

#2552 Fix compilation error in Draw String node when Zui is disabled
  Sources/armory/logicnode/DrawStringNode.hx
  blender/arm/logicnode/renderpath/LN_draw_string.py
Labels: Release Notes: Fixes

#2560 Remove no longer supported proxy system and add support for library overrides
  blender/arm/exporter.py
  blender/arm/handlers.py
  blender/arm/props.py
  blender/arm/props_traits.py
  blender/arm/props_traits_props.py
  blender/arm/props_ui.py
  blender/arm/proxy.py
  blender/arm/utils.py
Labels: Release Notes: Changes, Blender 3.3 LTS

#2561 Fix export of particle objects outside of the current scene and other collections
  blender/arm/exporter.py
Labels: Release Notes: Fixes

#2564 Created node for setting canvas input text.
  Sources/armory/logicnode/CanvasSetInputTextNode.hx
  blender/arm/logicnode/canvas/LN_set_canvas_input_text.py
Labels: Release Notes: Changes

#2557 Fix shape key export in optimized mesh export
  blender/arm/exporter_opt.py
  blender/arm/material/make_morph_target.py
Labels: Release Notes: Fixes
